### ISSUE TITLE
methode 

### ISSUE THREAD

**Issue by ultra1920** [abhn/marvel#2]
what's the name of methode (pca or svm or ..)

**Comment by abhn** [comment]
Local binary patterns (LBP) is used in my [example](https://github.com/abhn/marvel/blob/master/facerecognition/src/main/java/cultoftheunicorn/marvel/PersonRecognizer.java#L36), but you can easily switch it to PCA by using EigenFaceRecognizer.

**Comment by ultra1920** [comment]
How can I do that?

**Comment by abhn** [comment]
Haven't tested it, but try replacing

> faceRecognizer = com.googlecode.javacv.cpp.opencv_contrib.createLBPHFaceRecognizer(2,8,8,8,200);

With this 
> faceRecognizer = com.googlecode.javacv.cpp.opencv_contrib.createEigenFaceRecognizer(10,123.0);

[here](https://github.com/abhn/marvel/blob/master/facerecognition/src/main/java/cultoftheunicorn/marvel/PersonRecognizer.java#L36)
