### ISSUE TITLE
Demo APK link is broken !

### ISSUE THREAD

**Issue by RahulSDeshpande** [abhn/marvel#7]
Demo APK link https://goo.gl/UlTC0l is broken :)

**Comment by abhn** [comment]
Hey @RahulSDeshpande  thanks for reporting that. I'll fix it.

**Comment by RahulSDeshpande** [comment]
Cool man :)
Thanks

**Comment by abhn** [comment]
I've updated the link [with this](https://drive.google.com/open?id=1gRT05lNnGawxbmiXFgqmujd46QuqE-1n). Thanks
